name: MPundePhoto
favicon: null
layout_spectrum: 0.3923917799256742
typography_spectrum: 0.07544082240201533
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6145466493908316
  lightness: 0.3728665257804096
  saturation: 0.5110071669332683
  rhythmicContrast: 0.6359615260735154
purpose: []
